name: mercurius
description: For mercurius.

publish_to: "none"

version: 0.3.0+60

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter: # Flutter æœ¬ä½“ [ç½‘å€ç•¥]
    sdk: flutter
  flutter_localizations: # Flutter [ç½‘å€ç•¥]
    sdk: flutter
  another_flushbar: ^1.12.29 # æç¤ºæ¡† [https://pub.dev/packages/another_flushbar]
  badges: ^3.1.1 # å°çº¢ç‚¹æç¤º [https://pub.dev/packages/badges]
  confetti: ^0.7.0 # å½©çº¸æ•ˆæžœ [https://pub.dev/packages/confetti]
  cross_file: ^0.3.3+4 # æ–‡ä»¶æ“ä½œ [https://pub.dev/packages/cross_file]
  dio: ^5.1.1 # ç½‘ç»œè¯·æ±‚ [https://pub.dev/packages/dio]
  # TIPS: æžç¬‘çš„æ˜¯ï¼Œæˆ‘æƒ³å‡çº§ åŸºäºŽ intl ^0.18.0 çš„ table_calendarï¼Œä½† dart_date éœ€è¦ intl ^0.17.0
  # TIPS: è€Œ dart_date æœ€æ–°åŒ…è¿˜æ²¡åˆå¹¶æäº¤ï¼Œæ•…å°è¯• git æº
  # TIPS: é‡åˆ°äº† https://juejin.cn/post/6844903960625561613 é‡Œçš„é—®é¢˜åŽæˆåŠŸä½¿ç”¨äº† git
  # TIPS: ä½† flutter_localizations åˆæ˜¯éœ€è¦ intl 0.17.0 çš„
  # TIPS: æ‰€ä»¥æ‰¾åŒ…æ‰¾åˆ°äº† https://pub.dev/packages/flutter_localization è¿™ä¸ªåŒ…
  # TIPS: ä½†é‚£æ˜¯åˆ«äººå†™çš„åå­—å·®ä¸€ä¸ª `s` çš„åº“ï¼Œhttps://github.com/channdara/flutter_localization/issues/2 é‡Œä¹Ÿè¢«æžæ™•äº†
  # TIPS: æœ€åŽæ‰¾åˆ°äº†å®˜æ–¹çš„ issue è§ https://github.com/dart-lang/i18n/issues/458
  # TIPS: 2022-12-17 å°±æœ‰çš„é—®é¢˜ï¼ŒçŽ°åœ¨éƒ½ 2023-05-05 äº†ï¼Œ139 å¤©äº†è¿˜æ²¡æ›´æ–°ï¼Œéžå¸¸åå®˜æ–¹ðŸ˜¡
  # è½¬æ¢æ—¶é—´å·¥å…· [https://pub.dev/packages/dart_date]
  # git:
  #   url: https://github.com/spaznuski/dart_date.git
  dart_date: ^1.2.1
  # TIPS: è¦å‡çº§ file_picker çš„å‰ææ˜¯ share_plusï¼Œä¸ç”¨æ€¥äº†
  # TIPS: https://github.com/fluttercommunity/plus_plugins/commit/963686572d80d98d488b688108ca3899ef30d6e4 åœ¨ä¿®äº†
  file_picker: ^5.2.10 # æ–‡ä»¶é€‰æ‹© [https://pub.dev/packages/file_picker]
  flutter_displaymode: ^0.6.0 # é«˜åˆ· [https://pub.dev/packages/flutter_displaymode]
  flutter_markdown: ^0.6.14 # markdown [https://pub.dev/packages/flutter_markdown]
  flutter_quill: ^7.1.16 # å¯Œæ–‡æœ¬ [https://pub.dev/packages/flutter_quill]
  flutter_riverpod: ^2.3.1 # çŠ¶æ€ç®¡ç† [https://pub.dev/packages/riverpod]
  image_picker: ^0.8.7+4 # å›¾ç‰‡é€‰æ‹© [https://pub.dev/packages/image_picker]
  isar: ^3.1.0+1 # æ•°æ®åº“ [https://pub.dev/packages/isar]
  isar_flutter_libs: ^3.1.0+1 # æ•°æ®åº“çš„åº“ [https://pub.dev/packages/isar_flutter_libs]
  json_annotation: ^4.8.1 # json ç›¸å…³ [https://pub.dev/packages/json_annotation]
  keframe: ^3.0.0 # åˆ—è¡¨ä¼˜åŒ– [https://pub.dev/packages/keframe]
  loading_animation_widget: ^1.2.0+4 # åŠ è½½å™¨ç»„ä»¶ [https://pub.dev/packages/loading_animation_widget]
  open_app_file: ^4.0.1 # æ‰“å¼€æ–‡ä»¶ [https://pub.dev/packages/open_app_file]
  path_provider: ^2.0.14 # è·¯å¾„èŽ·å– [https://pub.dev/packages/path_provider]
  package_info_plus: ^3.1.2 # åŒ…ä¿¡æ¯ [https://pub.dev/packages/package_info_plus]
  photo_view: ^0.14.0 # å›¾ç‰‡è§†å›¾ [https://pub.dev/packages/photo_view]
  provider: ^6.0.5 # çŠ¶æ€ç®¡ç† [https://pub.dev/packages/provider]
  pull_to_refresh: ^2.0.0 # ä¸‹æ‹‰åˆ·æ–° [https://pub.dev/packages/pull_to_refresh]
  riverpod_annotation: ^2.0.1 # çŠ¶æ€ç®¡ç†ç›¸å…³ [https://pub.dev/packages/riverpod]
  share_plus: ^6.3.4 # åˆ†äº« [https://pub.dev/packages/share_plus]
  shared_preferences: ^2.1.0 # æ•°æ®æŒä¹…åŒ– [https://pub.dev/packages/shared_preferences]
  sticky_and_expandable_list: ^1.1.2 # ç²˜æ€§å¤´éƒ¨ä¸Žåˆ†ç»„åˆ—è¡¨ [https://pub.dev/packages/sticky_and_expandable_list]
  sudoku_solver_generator: ^2.1.0+1 # æ•°ç‹¬ç”Ÿæˆå™¨ [https://pub.dev/packages/sudoku_solver_generator]
  syncfusion_flutter_charts: ^21.2.3 # å›¾è¡¨ [https://pub.dev/packages/syncfusion_flutter_charts]
  table_calendar: ^3.0.8 # æ—¥åŽ† [https://pub.dev/packages/table_calendar]
  url_launcher: ^6.1.10 # æ‰“å¼€å¤–éƒ¨é“¾æŽ¥ [https://pub.dev/packages/url_launcher]
  unicons: ^2.1.1 # å›¾æ ‡ [https://pub.dev/packages/unicons]
  vibration: ^1.7.7 # æŒ¯åŠ¨åé¦ˆ [https://pub.dev/packages/vibration]
  waterfall_flow: ^3.0.2 # å›¾ç‰‡ç½‘æ ¼æµ [https://pub.dev/packages/waterfall_flow]

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 # ä»£ç ç”Ÿæˆç”¨å®žç”¨å·¥å…· [https://pub.dev/packages/build_runner]
  custom_lint: ^0.3.4 # è‡ªå®šä¹‰ lint [https://pub.dev/packages/custom_lint]
  isar_generator: ^3.1.0+1 # æ•°æ®åº“ä»£ç ç”Ÿæˆå·¥å…· [https://pub.dev/packages/isar_generator]
  json_serializable: ^6.6.2 # json ç›¸å…³ [https://pub.dev/packages/json_serializable]
  riverpod_generator: ^2.1.3 # riverpod ä»£ç ç”Ÿæˆå·¥å…· [https://pub.dev/packages/riverpod]
  riverpod_lint: ^1.1.5 # riverpod ä»£ç æ£€æŸ¥ [https://pub.dev/packages/riverpod]

flutter:
  uses-material-design: true # å¯ç”¨ material3 è®¾è®¡
  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira.ttf
    - family: QWeather_Icon
      fonts:
        - asset: assets/fonts/QWeather_Icons.ttf
  assets:
    - assets/icon/
    - assets/json/
